posts schema and model added
ognevoydev/Spring-Boot pull request #1
Opened 2022-12-01 14:48 UTC by ognevoydev

Добавил зависимости, создал схему для сущности объявления с помощью liquibase, написал модель сущности объявления.

2022-12-01 20:06 UTC, TiPo4u4eK requested changes

2022-12-01 20:06 UTC, TiPo4u4eK commented on src/main/resources/application.properties
> +spring.jpa.hibernate.show-sql=true
убери диалект (его автоматически подберёт Hibernate)
убери показывать sql (в проде такие логи часто недопустимы)

2022-12-01 20:06 UTC, TiPo4u4eK commented on src/main/resources/application.properties
> +spring.h2.console.enabled=true
откуда тут h2?

2022-12-02 06:36 UTC, ognevoydev commented on src/main/resources/db/changelog/create-posts-schema.yml
> +              - column:
Хотел чтобы пользователь мог указывать разный номер для объявлений, а не обязательно тот, который в профиле. Пользователя, который создал пост, думал потом сделать с авторизацией.

2022-12-02 14:14 UTC, TiPo4u4eK requested changes

2022-12-02 14:14 UTC, TiPo4u4eK commented on src/main/resources/application.yaml
> +  schema: public
schema обычно редко отличается от дефолтной (public), тч её можно не указывать
psql.username -> database.username, не нужно дублировать

2022-12-02 14:14 UTC, TiPo4u4eK commented on pom.xml
> +		<psql.version>42.5.1</psql.version>
psql - это утилита для терминала, а тут у тебя jdbc драйвер (обычно пишут postgres/postgresql)

2022-12-02 14:14 UTC, TiPo4u4eK commented on src/main/java/com/ognevoydev/springboot/models/Post.java
> -@Data
теперь нужно переопределить equals и hashCode

2022-12-02 14:14 UTC, TiPo4u4eK commented on src/main/resources/application.yaml
> +    url: jdbc:postgresql://${database.host}:${database.port}/${database.name}?currentSchema=${psql.schema}&user=${psql.user}&password=${psql.password}
креды не нужно указывать тут

2022-12-02 14:14 UTC, TiPo4u4eK commented on src/main/java/com/ognevoydev/springboot/models/Post.java
>  package com.ognevoydev.springboot.models;
dev.ognevoy.quisell.model

2022-12-02 14:36 UTC, ognevoydev commented on src/main/resources/db/changelog/create-posts-schema.yml
> +                    nullable: false
Да, чаще всего оно обязательно

2022-12-04 01:15 UTC, TiPo4u4eK requested changes

2022-12-04 01:15 UTC, TiPo4u4eK commented on pom.xml
>  	<description>Demo project for Spring Boot</description>
artifactId, name quisell
в description опиши кратко что это бек сервис для объявлений

2022-12-04 09:18 UTC, ognevoydev commented on src/main/resources/db/changelog/create-posts-schema.yml
> +              - column:
Телефон удалил, позже добавлю в таблице автора объявления

2022-12-04 14:51 UTC, TiPo4u4eK approved these changes

2022-12-04 14:52 UTC, merged